# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='stud_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jul.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='subj_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jul.Subject'),
            preserve_default=False,
        ),
    ]
