# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jul', '0002_auto_20160529_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('stud_id', 'subj_id')]),
        ),
    ]
